// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: services.proto
#ifndef GRPC_services_2eproto__INCLUDED
#define GRPC_services_2eproto__INCLUDED

#include "services.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace remote {

// functions definition
class PSIFunctions final {
 public:
  static constexpr char const* service_full_name() {
    return "remote.PSIFunctions";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status setup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::remote::AgreementRep* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>> Asyncsetup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>>(AsyncsetupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>> PrepareAsyncsetup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>>(PrepareAsyncsetupRaw(context, request, cq));
    }
    virtual ::grpc::Status encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::remote::EncryptRep* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>> Asyncencrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>>(AsyncencryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>> PrepareAsyncencrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>>(PrepareAsyncencryptRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void setup(::grpc::ClientContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setup(::grpc::ClientContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response, std::function<void(::grpc::Status)>) = 0;
      virtual void encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>* AsyncsetupRaw(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::remote::AgreementRep>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>* AsyncencryptRaw(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::remote::EncryptRep>* PrepareAsyncencryptRaw(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status setup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::remote::AgreementRep* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>> Asyncsetup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>>(AsyncsetupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>> PrepareAsyncsetup(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>>(PrepareAsyncsetupRaw(context, request, cq));
    }
    ::grpc::Status encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::remote::EncryptRep* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>> Asyncencrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>>(AsyncencryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>> PrepareAsyncencrypt(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>>(PrepareAsyncencryptRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void setup(::grpc::ClientContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response, std::function<void(::grpc::Status)>) override;
      void setup(::grpc::ClientContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response, ::grpc::ClientUnaryReactor* reactor) override;
      void encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response, std::function<void(::grpc::Status)>) override;
      void encrypt(::grpc::ClientContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>* AsyncsetupRaw(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::remote::AgreementRep>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::remote::AgreementReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>* AsyncencryptRaw(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::remote::EncryptRep>* PrepareAsyncencryptRaw(::grpc::ClientContext* context, const ::remote::EncryptReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_setup_;
    const ::grpc::internal::RpcMethod rpcmethod_encrypt_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status setup(::grpc::ServerContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response);
    virtual ::grpc::Status encrypt(::grpc::ServerContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::remote::AgreementReq* request, ::grpc::ServerAsyncResponseWriter< ::remote::AgreementRep>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_encrypt() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestencrypt(::grpc::ServerContext* context, ::remote::EncryptReq* request, ::grpc::ServerAsyncResponseWriter< ::remote::EncryptRep>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_setup<WithAsyncMethod_encrypt<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setup() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::remote::AgreementReq, ::remote::AgreementRep>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::remote::AgreementReq* request, ::remote::AgreementRep* response) { return this->setup(context, request, response); }));}
    void SetMessageAllocatorFor_setup(
        ::grpc::MessageAllocator< ::remote::AgreementReq, ::remote::AgreementRep>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::remote::AgreementReq, ::remote::AgreementRep>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setup(
      ::grpc::CallbackServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_encrypt() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::remote::EncryptReq, ::remote::EncryptRep>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::remote::EncryptReq* request, ::remote::EncryptRep* response) { return this->encrypt(context, request, response); }));}
    void SetMessageAllocatorFor_encrypt(
        ::grpc::MessageAllocator< ::remote::EncryptReq, ::remote::EncryptRep>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::remote::EncryptReq, ::remote::EncryptRep>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* encrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_setup<WithCallbackMethod_encrypt<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_encrypt() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setup() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_encrypt() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestencrypt(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setup() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setup(context, request, response); }));
    }
    ~WithRawCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_encrypt() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->encrypt(context, request, response); }));
    }
    ~WithRawCallbackMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* encrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::remote::AgreementReq, ::remote::AgreementRep>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::remote::AgreementReq, ::remote::AgreementRep>* streamer) {
                       return this->Streamedsetup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, const ::remote::AgreementReq* /*request*/, ::remote::AgreementRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsetup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::remote::AgreementReq,::remote::AgreementRep>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_encrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_encrypt() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::remote::EncryptReq, ::remote::EncryptRep>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::remote::EncryptReq, ::remote::EncryptRep>* streamer) {
                       return this->Streamedencrypt(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_encrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status encrypt(::grpc::ServerContext* /*context*/, const ::remote::EncryptReq* /*request*/, ::remote::EncryptRep* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedencrypt(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::remote::EncryptReq,::remote::EncryptRep>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_setup<WithStreamedUnaryMethod_encrypt<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_setup<WithStreamedUnaryMethod_encrypt<Service > > StreamedService;
};

}  // namespace remote


#endif  // GRPC_services_2eproto__INCLUDED
