// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_services_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_services_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_services_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_services_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_services_2eproto;
namespace remote {
class AgreementRep;
struct AgreementRepDefaultTypeInternal;
extern AgreementRepDefaultTypeInternal _AgreementRep_default_instance_;
class AgreementReq;
struct AgreementReqDefaultTypeInternal;
extern AgreementReqDefaultTypeInternal _AgreementReq_default_instance_;
}  // namespace remote
PROTOBUF_NAMESPACE_OPEN
template<> ::remote::AgreementRep* Arena::CreateMaybeMessage<::remote::AgreementRep>(Arena*);
template<> ::remote::AgreementReq* Arena::CreateMaybeMessage<::remote::AgreementReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace remote {

// ===================================================================

class AgreementReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:remote.AgreementReq) */ {
 public:
  inline AgreementReq() : AgreementReq(nullptr) {}
  ~AgreementReq() override;
  explicit PROTOBUF_CONSTEXPR AgreementReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgreementReq(const AgreementReq& from);
  AgreementReq(AgreementReq&& from) noexcept
    : AgreementReq() {
    *this = ::std::move(from);
  }

  inline AgreementReq& operator=(const AgreementReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgreementReq& operator=(AgreementReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgreementReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgreementReq* internal_default_instance() {
    return reinterpret_cast<const AgreementReq*>(
               &_AgreementReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AgreementReq& a, AgreementReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AgreementReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgreementReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgreementReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgreementReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgreementReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgreementReq& from) {
    AgreementReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgreementReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "remote.AgreementReq";
  }
  protected:
  explicit AgreementReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:remote.AgreementReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_services_2eproto;
};
// -------------------------------------------------------------------

class AgreementRep final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:remote.AgreementRep) */ {
 public:
  inline AgreementRep() : AgreementRep(nullptr) {}
  ~AgreementRep() override;
  explicit PROTOBUF_CONSTEXPR AgreementRep(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgreementRep(const AgreementRep& from);
  AgreementRep(AgreementRep&& from) noexcept
    : AgreementRep() {
    *this = ::std::move(from);
  }

  inline AgreementRep& operator=(const AgreementRep& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgreementRep& operator=(AgreementRep&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgreementRep& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgreementRep* internal_default_instance() {
    return reinterpret_cast<const AgreementRep*>(
               &_AgreementRep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AgreementRep& a, AgreementRep& b) {
    a.Swap(&b);
  }
  inline void Swap(AgreementRep* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgreementRep* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgreementRep* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgreementRep>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgreementRep& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgreementRep& from) {
    AgreementRep::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgreementRep* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "remote.AgreementRep";
  }
  protected:
  explicit AgreementRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPubFieldNumber = 1,
    kRelFieldNumber = 2,
    kParFieldNumber = 3,
  };
  // string pub = 1;
  void clear_pub();
  const std::string& pub() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pub(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pub();
  PROTOBUF_NODISCARD std::string* release_pub();
  void set_allocated_pub(std::string* pub);
  private:
  const std::string& _internal_pub() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pub(const std::string& value);
  std::string* _internal_mutable_pub();
  public:

  // string rel = 2;
  void clear_rel();
  const std::string& rel() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rel(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rel();
  PROTOBUF_NODISCARD std::string* release_rel();
  void set_allocated_rel(std::string* rel);
  private:
  const std::string& _internal_rel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rel(const std::string& value);
  std::string* _internal_mutable_rel();
  public:

  // string par = 3;
  void clear_par();
  const std::string& par() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_par(ArgT0&& arg0, ArgT... args);
  std::string* mutable_par();
  PROTOBUF_NODISCARD std::string* release_par();
  void set_allocated_par(std::string* par);
  private:
  const std::string& _internal_par() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_par(const std::string& value);
  std::string* _internal_mutable_par();
  public:

  // @@protoc_insertion_point(class_scope:remote.AgreementRep)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pub_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rel_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr par_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_services_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AgreementReq

// string name = 1;
inline void AgreementReq::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& AgreementReq::name() const {
  // @@protoc_insertion_point(field_get:remote.AgreementReq.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AgreementReq::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:remote.AgreementReq.name)
}
inline std::string* AgreementReq::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:remote.AgreementReq.name)
  return _s;
}
inline const std::string& AgreementReq::_internal_name() const {
  return _impl_.name_.Get();
}
inline void AgreementReq::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* AgreementReq::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* AgreementReq::release_name() {
  // @@protoc_insertion_point(field_release:remote.AgreementReq.name)
  return _impl_.name_.Release();
}
inline void AgreementReq::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:remote.AgreementReq.name)
}

// -------------------------------------------------------------------

// AgreementRep

// string pub = 1;
inline void AgreementRep::clear_pub() {
  _impl_.pub_.ClearToEmpty();
}
inline const std::string& AgreementRep::pub() const {
  // @@protoc_insertion_point(field_get:remote.AgreementRep.pub)
  return _internal_pub();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AgreementRep::set_pub(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pub_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:remote.AgreementRep.pub)
}
inline std::string* AgreementRep::mutable_pub() {
  std::string* _s = _internal_mutable_pub();
  // @@protoc_insertion_point(field_mutable:remote.AgreementRep.pub)
  return _s;
}
inline const std::string& AgreementRep::_internal_pub() const {
  return _impl_.pub_.Get();
}
inline void AgreementRep::_internal_set_pub(const std::string& value) {
  
  _impl_.pub_.Set(value, GetArenaForAllocation());
}
inline std::string* AgreementRep::_internal_mutable_pub() {
  
  return _impl_.pub_.Mutable(GetArenaForAllocation());
}
inline std::string* AgreementRep::release_pub() {
  // @@protoc_insertion_point(field_release:remote.AgreementRep.pub)
  return _impl_.pub_.Release();
}
inline void AgreementRep::set_allocated_pub(std::string* pub) {
  if (pub != nullptr) {
    
  } else {
    
  }
  _impl_.pub_.SetAllocated(pub, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pub_.IsDefault()) {
    _impl_.pub_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:remote.AgreementRep.pub)
}

// string rel = 2;
inline void AgreementRep::clear_rel() {
  _impl_.rel_.ClearToEmpty();
}
inline const std::string& AgreementRep::rel() const {
  // @@protoc_insertion_point(field_get:remote.AgreementRep.rel)
  return _internal_rel();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AgreementRep::set_rel(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rel_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:remote.AgreementRep.rel)
}
inline std::string* AgreementRep::mutable_rel() {
  std::string* _s = _internal_mutable_rel();
  // @@protoc_insertion_point(field_mutable:remote.AgreementRep.rel)
  return _s;
}
inline const std::string& AgreementRep::_internal_rel() const {
  return _impl_.rel_.Get();
}
inline void AgreementRep::_internal_set_rel(const std::string& value) {
  
  _impl_.rel_.Set(value, GetArenaForAllocation());
}
inline std::string* AgreementRep::_internal_mutable_rel() {
  
  return _impl_.rel_.Mutable(GetArenaForAllocation());
}
inline std::string* AgreementRep::release_rel() {
  // @@protoc_insertion_point(field_release:remote.AgreementRep.rel)
  return _impl_.rel_.Release();
}
inline void AgreementRep::set_allocated_rel(std::string* rel) {
  if (rel != nullptr) {
    
  } else {
    
  }
  _impl_.rel_.SetAllocated(rel, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rel_.IsDefault()) {
    _impl_.rel_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:remote.AgreementRep.rel)
}

// string par = 3;
inline void AgreementRep::clear_par() {
  _impl_.par_.ClearToEmpty();
}
inline const std::string& AgreementRep::par() const {
  // @@protoc_insertion_point(field_get:remote.AgreementRep.par)
  return _internal_par();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AgreementRep::set_par(ArgT0&& arg0, ArgT... args) {
 
 _impl_.par_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:remote.AgreementRep.par)
}
inline std::string* AgreementRep::mutable_par() {
  std::string* _s = _internal_mutable_par();
  // @@protoc_insertion_point(field_mutable:remote.AgreementRep.par)
  return _s;
}
inline const std::string& AgreementRep::_internal_par() const {
  return _impl_.par_.Get();
}
inline void AgreementRep::_internal_set_par(const std::string& value) {
  
  _impl_.par_.Set(value, GetArenaForAllocation());
}
inline std::string* AgreementRep::_internal_mutable_par() {
  
  return _impl_.par_.Mutable(GetArenaForAllocation());
}
inline std::string* AgreementRep::release_par() {
  // @@protoc_insertion_point(field_release:remote.AgreementRep.par)
  return _impl_.par_.Release();
}
inline void AgreementRep::set_allocated_par(std::string* par) {
  if (par != nullptr) {
    
  } else {
    
  }
  _impl_.par_.SetAllocated(par, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.par_.IsDefault()) {
    _impl_.par_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:remote.AgreementRep.par)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace remote

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_services_2eproto
