// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

#include "services.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace remote {
PROTOBUF_CONSTEXPR EncryptReq::EncryptReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.file_to_encrypt_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.agreement_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EncryptReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncryptReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptReqDefaultTypeInternal() {}
  union {
    EncryptReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptReqDefaultTypeInternal _EncryptReq_default_instance_;
PROTOBUF_CONSTEXPR Ciphertexts::Ciphertexts(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.cipher_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CiphertextsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CiphertextsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CiphertextsDefaultTypeInternal() {}
  union {
    Ciphertexts _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CiphertextsDefaultTypeInternal _Ciphertexts_default_instance_;
PROTOBUF_CONSTEXPR EncryptRep::EncryptRep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ciphertexts_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EncryptRepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncryptRepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptRepDefaultTypeInternal() {}
  union {
    EncryptRep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptRepDefaultTypeInternal _EncryptRep_default_instance_;
PROTOBUF_CONSTEXPR AgreementReq::AgreementReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.poly_modulus_degree_)*/int64_t{0}
  , /*decltype(_impl_.plain_modulus_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgreementReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgreementReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgreementReqDefaultTypeInternal() {}
  union {
    AgreementReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgreementReqDefaultTypeInternal _AgreementReq_default_instance_;
PROTOBUF_CONSTEXPR AgreementRep::AgreementRep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pub_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rel_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.par_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgreementRepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgreementRepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgreementRepDefaultTypeInternal() {}
  union {
    AgreementRep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgreementRepDefaultTypeInternal _AgreementRep_default_instance_;
}  // namespace remote
static ::_pb::Metadata file_level_metadata_services_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_services_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_services_2eproto = nullptr;

const uint32_t TableStruct_services_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::EncryptReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::EncryptReq, _impl_.file_to_encrypt_),
  PROTOBUF_FIELD_OFFSET(::remote::EncryptReq, _impl_.agreement_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::Ciphertexts, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::Ciphertexts, _impl_.cipher_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::EncryptRep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::EncryptRep, _impl_.ciphertexts_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _impl_.poly_modulus_degree_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _impl_.plain_modulus_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.pub_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.rel_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.par_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::remote::EncryptReq)},
  { 8, -1, -1, sizeof(::remote::Ciphertexts)},
  { 15, -1, -1, sizeof(::remote::EncryptRep)},
  { 22, -1, -1, sizeof(::remote::AgreementReq)},
  { 31, -1, -1, sizeof(::remote::AgreementRep)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::remote::_EncryptReq_default_instance_._instance,
  &::remote::_Ciphertexts_default_instance_._instance,
  &::remote::_EncryptRep_default_instance_._instance,
  &::remote::_AgreementReq_default_instance_._instance,
  &::remote::_AgreementRep_default_instance_._instance,
};

const char descriptor_table_protodef_services_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016services.proto\022\006remote\"=\n\nEncryptReq\022\027"
  "\n\017file_to_encrypt\030\001 \001(\t\022\026\n\016agreement_nam"
  "e\030\002 \001(\t\"\035\n\013Ciphertexts\022\016\n\006cipher\030\001 \003(\014\"6"
  "\n\nEncryptRep\022(\n\013ciphertexts\030\001 \001(\0132\023.remo"
  "te.Ciphertexts\"P\n\014AgreementReq\022\014\n\004name\030\001"
  " \001(\t\022\033\n\023poly_modulus_degree\030\002 \001(\003\022\025\n\rpla"
  "in_modulus\030\003 \001(\003\"5\n\014AgreementRep\022\013\n\003pub\030"
  "\001 \001(\014\022\013\n\003rel\030\002 \001(\014\022\013\n\003par\030\003 \001(\0142z\n\014PSIFu"
  "nctions\0225\n\005setup\022\024.remote.AgreementReq\032\024"
  ".remote.AgreementRep\"\000\0223\n\007encrypt\022\022.remo"
  "te.EncryptReq\032\022.remote.EncryptRep\"\000b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_services_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_services_2eproto = {
    false, false, 443, descriptor_table_protodef_services_2eproto,
    "services.proto",
    &descriptor_table_services_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_services_2eproto::offsets,
    file_level_metadata_services_2eproto, file_level_enum_descriptors_services_2eproto,
    file_level_service_descriptors_services_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_services_2eproto_getter() {
  return &descriptor_table_services_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_services_2eproto(&descriptor_table_services_2eproto);
namespace remote {

// ===================================================================

class EncryptReq::_Internal {
 public:
};

EncryptReq::EncryptReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.EncryptReq)
}
EncryptReq::EncryptReq(const EncryptReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EncryptReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.file_to_encrypt_){}
    , decltype(_impl_.agreement_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.file_to_encrypt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_to_encrypt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_file_to_encrypt().empty()) {
    _this->_impl_.file_to_encrypt_.Set(from._internal_file_to_encrypt(), 
      _this->GetArenaForAllocation());
  }
  _impl_.agreement_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agreement_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_agreement_name().empty()) {
    _this->_impl_.agreement_name_.Set(from._internal_agreement_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:remote.EncryptReq)
}

inline void EncryptReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.file_to_encrypt_){}
    , decltype(_impl_.agreement_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.file_to_encrypt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_to_encrypt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.agreement_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agreement_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EncryptReq::~EncryptReq() {
  // @@protoc_insertion_point(destructor:remote.EncryptReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EncryptReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.file_to_encrypt_.Destroy();
  _impl_.agreement_name_.Destroy();
}

void EncryptReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EncryptReq::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.EncryptReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_to_encrypt_.ClearToEmpty();
  _impl_.agreement_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EncryptReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string file_to_encrypt = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_file_to_encrypt();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.EncryptReq.file_to_encrypt"));
        } else
          goto handle_unusual;
        continue;
      // string agreement_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_agreement_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.EncryptReq.agreement_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EncryptReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.EncryptReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string file_to_encrypt = 1;
  if (!this->_internal_file_to_encrypt().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_file_to_encrypt().data(), static_cast<int>(this->_internal_file_to_encrypt().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.EncryptReq.file_to_encrypt");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_file_to_encrypt(), target);
  }

  // string agreement_name = 2;
  if (!this->_internal_agreement_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_agreement_name().data(), static_cast<int>(this->_internal_agreement_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.EncryptReq.agreement_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_agreement_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.EncryptReq)
  return target;
}

size_t EncryptReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.EncryptReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string file_to_encrypt = 1;
  if (!this->_internal_file_to_encrypt().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_file_to_encrypt());
  }

  // string agreement_name = 2;
  if (!this->_internal_agreement_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_agreement_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EncryptReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EncryptReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EncryptReq::GetClassData() const { return &_class_data_; }


void EncryptReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EncryptReq*>(&to_msg);
  auto& from = static_cast<const EncryptReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.EncryptReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_to_encrypt().empty()) {
    _this->_internal_set_file_to_encrypt(from._internal_file_to_encrypt());
  }
  if (!from._internal_agreement_name().empty()) {
    _this->_internal_set_agreement_name(from._internal_agreement_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EncryptReq::CopyFrom(const EncryptReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.EncryptReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncryptReq::IsInitialized() const {
  return true;
}

void EncryptReq::InternalSwap(EncryptReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.file_to_encrypt_, lhs_arena,
      &other->_impl_.file_to_encrypt_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.agreement_name_, lhs_arena,
      &other->_impl_.agreement_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata EncryptReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[0]);
}

// ===================================================================

class Ciphertexts::_Internal {
 public:
};

Ciphertexts::Ciphertexts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.Ciphertexts)
}
Ciphertexts::Ciphertexts(const Ciphertexts& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Ciphertexts* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.cipher_){from._impl_.cipher_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:remote.Ciphertexts)
}

inline void Ciphertexts::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.cipher_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Ciphertexts::~Ciphertexts() {
  // @@protoc_insertion_point(destructor:remote.Ciphertexts)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ciphertexts::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.cipher_.~RepeatedPtrField();
}

void Ciphertexts::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Ciphertexts::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.Ciphertexts)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cipher_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ciphertexts::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated bytes cipher = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_cipher();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ciphertexts::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.Ciphertexts)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes cipher = 1;
  for (int i = 0, n = this->_internal_cipher_size(); i < n; i++) {
    const auto& s = this->_internal_cipher(i);
    target = stream->WriteBytes(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.Ciphertexts)
  return target;
}

size_t Ciphertexts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.Ciphertexts)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes cipher = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.cipher_.size());
  for (int i = 0, n = _impl_.cipher_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      _impl_.cipher_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ciphertexts::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Ciphertexts::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ciphertexts::GetClassData() const { return &_class_data_; }


void Ciphertexts::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Ciphertexts*>(&to_msg);
  auto& from = static_cast<const Ciphertexts&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.Ciphertexts)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.cipher_.MergeFrom(from._impl_.cipher_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ciphertexts::CopyFrom(const Ciphertexts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.Ciphertexts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ciphertexts::IsInitialized() const {
  return true;
}

void Ciphertexts::InternalSwap(Ciphertexts* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.cipher_.InternalSwap(&other->_impl_.cipher_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Ciphertexts::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[1]);
}

// ===================================================================

class EncryptRep::_Internal {
 public:
  static const ::remote::Ciphertexts& ciphertexts(const EncryptRep* msg);
};

const ::remote::Ciphertexts&
EncryptRep::_Internal::ciphertexts(const EncryptRep* msg) {
  return *msg->_impl_.ciphertexts_;
}
EncryptRep::EncryptRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.EncryptRep)
}
EncryptRep::EncryptRep(const EncryptRep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EncryptRep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ciphertexts_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_ciphertexts()) {
    _this->_impl_.ciphertexts_ = new ::remote::Ciphertexts(*from._impl_.ciphertexts_);
  }
  // @@protoc_insertion_point(copy_constructor:remote.EncryptRep)
}

inline void EncryptRep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ciphertexts_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EncryptRep::~EncryptRep() {
  // @@protoc_insertion_point(destructor:remote.EncryptRep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EncryptRep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.ciphertexts_;
}

void EncryptRep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EncryptRep::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.EncryptRep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.ciphertexts_ != nullptr) {
    delete _impl_.ciphertexts_;
  }
  _impl_.ciphertexts_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EncryptRep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .remote.Ciphertexts ciphertexts = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_ciphertexts(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EncryptRep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.EncryptRep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .remote.Ciphertexts ciphertexts = 1;
  if (this->_internal_has_ciphertexts()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::ciphertexts(this),
        _Internal::ciphertexts(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.EncryptRep)
  return target;
}

size_t EncryptRep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.EncryptRep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .remote.Ciphertexts ciphertexts = 1;
  if (this->_internal_has_ciphertexts()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ciphertexts_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EncryptRep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EncryptRep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EncryptRep::GetClassData() const { return &_class_data_; }


void EncryptRep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EncryptRep*>(&to_msg);
  auto& from = static_cast<const EncryptRep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.EncryptRep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_ciphertexts()) {
    _this->_internal_mutable_ciphertexts()->::remote::Ciphertexts::MergeFrom(
        from._internal_ciphertexts());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EncryptRep::CopyFrom(const EncryptRep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.EncryptRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncryptRep::IsInitialized() const {
  return true;
}

void EncryptRep::InternalSwap(EncryptRep* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.ciphertexts_, other->_impl_.ciphertexts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EncryptRep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[2]);
}

// ===================================================================

class AgreementReq::_Internal {
 public:
};

AgreementReq::AgreementReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.AgreementReq)
}
AgreementReq::AgreementReq(const AgreementReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgreementReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.poly_modulus_degree_){}
    , decltype(_impl_.plain_modulus_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.poly_modulus_degree_, &from._impl_.poly_modulus_degree_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.plain_modulus_) -
    reinterpret_cast<char*>(&_impl_.poly_modulus_degree_)) + sizeof(_impl_.plain_modulus_));
  // @@protoc_insertion_point(copy_constructor:remote.AgreementReq)
}

inline void AgreementReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.poly_modulus_degree_){int64_t{0}}
    , decltype(_impl_.plain_modulus_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgreementReq::~AgreementReq() {
  // @@protoc_insertion_point(destructor:remote.AgreementReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgreementReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void AgreementReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgreementReq::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.AgreementReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.poly_modulus_degree_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.plain_modulus_) -
      reinterpret_cast<char*>(&_impl_.poly_modulus_degree_)) + sizeof(_impl_.plain_modulus_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgreementReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.AgreementReq.name"));
        } else
          goto handle_unusual;
        continue;
      // int64 poly_modulus_degree = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.poly_modulus_degree_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 plain_modulus = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.plain_modulus_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgreementReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.AgreementReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.AgreementReq.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int64 poly_modulus_degree = 2;
  if (this->_internal_poly_modulus_degree() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_poly_modulus_degree(), target);
  }

  // int64 plain_modulus = 3;
  if (this->_internal_plain_modulus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_plain_modulus(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.AgreementReq)
  return target;
}

size_t AgreementReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.AgreementReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int64 poly_modulus_degree = 2;
  if (this->_internal_poly_modulus_degree() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_poly_modulus_degree());
  }

  // int64 plain_modulus = 3;
  if (this->_internal_plain_modulus() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_plain_modulus());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgreementReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgreementReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgreementReq::GetClassData() const { return &_class_data_; }


void AgreementReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgreementReq*>(&to_msg);
  auto& from = static_cast<const AgreementReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.AgreementReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_poly_modulus_degree() != 0) {
    _this->_internal_set_poly_modulus_degree(from._internal_poly_modulus_degree());
  }
  if (from._internal_plain_modulus() != 0) {
    _this->_internal_set_plain_modulus(from._internal_plain_modulus());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgreementReq::CopyFrom(const AgreementReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.AgreementReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgreementReq::IsInitialized() const {
  return true;
}

void AgreementReq::InternalSwap(AgreementReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AgreementReq, _impl_.plain_modulus_)
      + sizeof(AgreementReq::_impl_.plain_modulus_)
      - PROTOBUF_FIELD_OFFSET(AgreementReq, _impl_.poly_modulus_degree_)>(
          reinterpret_cast<char*>(&_impl_.poly_modulus_degree_),
          reinterpret_cast<char*>(&other->_impl_.poly_modulus_degree_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AgreementReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[3]);
}

// ===================================================================

class AgreementRep::_Internal {
 public:
};

AgreementRep::AgreementRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.AgreementRep)
}
AgreementRep::AgreementRep(const AgreementRep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgreementRep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pub_){}
    , decltype(_impl_.rel_){}
    , decltype(_impl_.par_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.pub_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pub_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pub().empty()) {
    _this->_impl_.pub_.Set(from._internal_pub(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rel().empty()) {
    _this->_impl_.rel_.Set(from._internal_rel(), 
      _this->GetArenaForAllocation());
  }
  _impl_.par_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.par_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_par().empty()) {
    _this->_impl_.par_.Set(from._internal_par(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:remote.AgreementRep)
}

inline void AgreementRep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pub_){}
    , decltype(_impl_.rel_){}
    , decltype(_impl_.par_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.pub_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pub_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.par_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.par_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgreementRep::~AgreementRep() {
  // @@protoc_insertion_point(destructor:remote.AgreementRep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgreementRep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pub_.Destroy();
  _impl_.rel_.Destroy();
  _impl_.par_.Destroy();
}

void AgreementRep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgreementRep::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.AgreementRep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pub_.ClearToEmpty();
  _impl_.rel_.ClearToEmpty();
  _impl_.par_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgreementRep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes pub = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_pub();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes rel = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_rel();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes par = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_par();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgreementRep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.AgreementRep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes pub = 1;
  if (!this->_internal_pub().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_pub(), target);
  }

  // bytes rel = 2;
  if (!this->_internal_rel().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_rel(), target);
  }

  // bytes par = 3;
  if (!this->_internal_par().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_par(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.AgreementRep)
  return target;
}

size_t AgreementRep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.AgreementRep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes pub = 1;
  if (!this->_internal_pub().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_pub());
  }

  // bytes rel = 2;
  if (!this->_internal_rel().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rel());
  }

  // bytes par = 3;
  if (!this->_internal_par().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_par());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgreementRep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgreementRep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgreementRep::GetClassData() const { return &_class_data_; }


void AgreementRep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgreementRep*>(&to_msg);
  auto& from = static_cast<const AgreementRep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.AgreementRep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pub().empty()) {
    _this->_internal_set_pub(from._internal_pub());
  }
  if (!from._internal_rel().empty()) {
    _this->_internal_set_rel(from._internal_rel());
  }
  if (!from._internal_par().empty()) {
    _this->_internal_set_par(from._internal_par());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgreementRep::CopyFrom(const AgreementRep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.AgreementRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgreementRep::IsInitialized() const {
  return true;
}

void AgreementRep::InternalSwap(AgreementRep* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pub_, lhs_arena,
      &other->_impl_.pub_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rel_, lhs_arena,
      &other->_impl_.rel_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.par_, lhs_arena,
      &other->_impl_.par_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AgreementRep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace remote
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::remote::EncryptReq*
Arena::CreateMaybeMessage< ::remote::EncryptReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::EncryptReq >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::Ciphertexts*
Arena::CreateMaybeMessage< ::remote::Ciphertexts >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::Ciphertexts >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::EncryptRep*
Arena::CreateMaybeMessage< ::remote::EncryptRep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::EncryptRep >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::AgreementReq*
Arena::CreateMaybeMessage< ::remote::AgreementReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::AgreementReq >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::AgreementRep*
Arena::CreateMaybeMessage< ::remote::AgreementRep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::AgreementRep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
