// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

#include "services.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace remote {
PROTOBUF_CONSTEXPR AgreementReq::AgreementReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgreementReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgreementReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgreementReqDefaultTypeInternal() {}
  union {
    AgreementReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgreementReqDefaultTypeInternal _AgreementReq_default_instance_;
PROTOBUF_CONSTEXPR AgreementRep::AgreementRep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pub_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rel_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.par_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgreementRepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgreementRepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgreementRepDefaultTypeInternal() {}
  union {
    AgreementRep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgreementRepDefaultTypeInternal _AgreementRep_default_instance_;
}  // namespace remote
static ::_pb::Metadata file_level_metadata_services_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_services_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_services_2eproto = nullptr;

const uint32_t TableStruct_services_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementReq, _impl_.name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.pub_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.rel_),
  PROTOBUF_FIELD_OFFSET(::remote::AgreementRep, _impl_.par_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::remote::AgreementReq)},
  { 7, -1, -1, sizeof(::remote::AgreementRep)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::remote::_AgreementReq_default_instance_._instance,
  &::remote::_AgreementRep_default_instance_._instance,
};

const char descriptor_table_protodef_services_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016services.proto\022\006remote\"\034\n\014AgreementReq"
  "\022\014\n\004name\030\001 \001(\t\"5\n\014AgreementRep\022\013\n\003pub\030\001 "
  "\001(\t\022\013\n\003rel\030\002 \001(\t\022\013\n\003par\030\003 \001(\t2E\n\014PSIFunc"
  "tions\0225\n\005setup\022\024.remote.AgreementReq\032\024.r"
  "emote.AgreementRep\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_services_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_services_2eproto = {
    false, false, 188, descriptor_table_protodef_services_2eproto,
    "services.proto",
    &descriptor_table_services_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_services_2eproto::offsets,
    file_level_metadata_services_2eproto, file_level_enum_descriptors_services_2eproto,
    file_level_service_descriptors_services_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_services_2eproto_getter() {
  return &descriptor_table_services_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_services_2eproto(&descriptor_table_services_2eproto);
namespace remote {

// ===================================================================

class AgreementReq::_Internal {
 public:
};

AgreementReq::AgreementReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.AgreementReq)
}
AgreementReq::AgreementReq(const AgreementReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgreementReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:remote.AgreementReq)
}

inline void AgreementReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgreementReq::~AgreementReq() {
  // @@protoc_insertion_point(destructor:remote.AgreementReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgreementReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void AgreementReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgreementReq::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.AgreementReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgreementReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.AgreementReq.name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgreementReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.AgreementReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.AgreementReq.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.AgreementReq)
  return target;
}

size_t AgreementReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.AgreementReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgreementReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgreementReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgreementReq::GetClassData() const { return &_class_data_; }


void AgreementReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgreementReq*>(&to_msg);
  auto& from = static_cast<const AgreementReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.AgreementReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgreementReq::CopyFrom(const AgreementReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.AgreementReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgreementReq::IsInitialized() const {
  return true;
}

void AgreementReq::InternalSwap(AgreementReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AgreementReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[0]);
}

// ===================================================================

class AgreementRep::_Internal {
 public:
};

AgreementRep::AgreementRep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:remote.AgreementRep)
}
AgreementRep::AgreementRep(const AgreementRep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgreementRep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pub_){}
    , decltype(_impl_.rel_){}
    , decltype(_impl_.par_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.pub_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pub_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pub().empty()) {
    _this->_impl_.pub_.Set(from._internal_pub(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rel().empty()) {
    _this->_impl_.rel_.Set(from._internal_rel(), 
      _this->GetArenaForAllocation());
  }
  _impl_.par_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.par_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_par().empty()) {
    _this->_impl_.par_.Set(from._internal_par(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:remote.AgreementRep)
}

inline void AgreementRep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pub_){}
    , decltype(_impl_.rel_){}
    , decltype(_impl_.par_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.pub_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pub_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.par_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.par_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgreementRep::~AgreementRep() {
  // @@protoc_insertion_point(destructor:remote.AgreementRep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgreementRep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pub_.Destroy();
  _impl_.rel_.Destroy();
  _impl_.par_.Destroy();
}

void AgreementRep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgreementRep::Clear() {
// @@protoc_insertion_point(message_clear_start:remote.AgreementRep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pub_.ClearToEmpty();
  _impl_.rel_.ClearToEmpty();
  _impl_.par_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgreementRep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string pub = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_pub();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.AgreementRep.pub"));
        } else
          goto handle_unusual;
        continue;
      // string rel = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_rel();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.AgreementRep.rel"));
        } else
          goto handle_unusual;
        continue;
      // string par = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_par();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "remote.AgreementRep.par"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgreementRep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:remote.AgreementRep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string pub = 1;
  if (!this->_internal_pub().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pub().data(), static_cast<int>(this->_internal_pub().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.AgreementRep.pub");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_pub(), target);
  }

  // string rel = 2;
  if (!this->_internal_rel().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rel().data(), static_cast<int>(this->_internal_rel().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.AgreementRep.rel");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_rel(), target);
  }

  // string par = 3;
  if (!this->_internal_par().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_par().data(), static_cast<int>(this->_internal_par().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "remote.AgreementRep.par");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_par(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:remote.AgreementRep)
  return target;
}

size_t AgreementRep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:remote.AgreementRep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pub = 1;
  if (!this->_internal_pub().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pub());
  }

  // string rel = 2;
  if (!this->_internal_rel().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rel());
  }

  // string par = 3;
  if (!this->_internal_par().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_par());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgreementRep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgreementRep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgreementRep::GetClassData() const { return &_class_data_; }


void AgreementRep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgreementRep*>(&to_msg);
  auto& from = static_cast<const AgreementRep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:remote.AgreementRep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pub().empty()) {
    _this->_internal_set_pub(from._internal_pub());
  }
  if (!from._internal_rel().empty()) {
    _this->_internal_set_rel(from._internal_rel());
  }
  if (!from._internal_par().empty()) {
    _this->_internal_set_par(from._internal_par());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgreementRep::CopyFrom(const AgreementRep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:remote.AgreementRep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgreementRep::IsInitialized() const {
  return true;
}

void AgreementRep::InternalSwap(AgreementRep* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pub_, lhs_arena,
      &other->_impl_.pub_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rel_, lhs_arena,
      &other->_impl_.rel_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.par_, lhs_arena,
      &other->_impl_.par_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AgreementRep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2eproto_getter, &descriptor_table_services_2eproto_once,
      file_level_metadata_services_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace remote
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::remote::AgreementReq*
Arena::CreateMaybeMessage< ::remote::AgreementReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::AgreementReq >(arena);
}
template<> PROTOBUF_NOINLINE ::remote::AgreementRep*
Arena::CreateMaybeMessage< ::remote::AgreementRep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::remote::AgreementRep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
